theme: jekyll-theme-tactile
title: Welcome to the Bioinformatics Research Network!
description: Need a project? Join one. Have a project? Invite collaborators. BRN is a space for connecting projects and collaborators.
